kind: Namespace
apiVersion: v1
metadata:
  name: unqweb-app
---
apiVersion: v1
kind: Service
metadata:
  name: unqweb-app
  namespace: unqweb-app
spec:
  type: NodePort
  selector:
    app: unqweb-app
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unqweb-app
  namespace: unqweb-app
  labels:
    app: unqweb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unqweb-app
  template:
    metadata:
      labels:
        app: unqweb-app
    spec:
      containers:
      - name: unqweb-app
        image: sharkshashi/unqwebapp:1.0.4
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
